### ISSUE TITLE
Lack of Include files

### ISSUE THREAD

**Issue by fede-vaccaro** [rikardolajos/clouds#1]
Hi! I wanted to implement volumetric clouds in my OpenGL demo, so I found your master thesis and I'm reading it. Then I found this repo and I did a git clone to try it, but lacks of Include/ folder or files. Also even libraries, I suppose. Can you upload it here? Thank you!

**Comment by rikardolajos** [comment]
Hi!
I'm glad to hear that you are looking at my stuff. The files missing are from GLM, SDL and GLEW which are not really part of the master thesis. That is why I left them out. I will see if I can get it working and put up a separate branch with the libraries included (it has been some time since it tried this code). The code is a bit bad and not very clean but that is what you get when the thesis is due ;) .

As I mentioned in my report I got around 40 fps with my implementation so might want to improve that if you are going to have other stuff as well in the scene and not only clouds like I had. You will need the cloud textures as well which I generated with my noisegen package so we will need to get that running as well.

You could also try you own implementation and using my thesis and code as reference. That might end up being faster and easier to understand, but I will make a try at getting the old code running.
//Rikard

**Comment by rikardolajos** [comment]
So I have added a branch with the required dependencies and resources: https://github.com/rikardolajos/clouds/tree/with_libs_and_resources

For me it compiles but there is something that is wrong because it is badly zoomed in. It might be because I developed everything for an Nvidia card but my personal computer runs with an AMD and there can be something I have missed.

Good luck with your demo! If you have any questions don't hesitate and if you end up using my stuff don't forget to say where you got it from ;)

//Rikard

**Comment by fede-vaccaro** [comment]
Hi, thank you for you're answer! I'll try it soon. Onestly I don't know if I'll "steal" part of your code. Currently I'm studying (and trying to implement) Horizon Zero Down Volumetric Clouds from GPU Pro 7. It's quite advanced to me (I just had a course at the University but I'm continuing to exploring this field), but finding your thesis definitively helped me figuring out certain things! 

Also I found interesting this : https://github.com/NadirRoGue/RenderEngine https://www.youtube.com/watch?v=U1VEJsVS7eE&t=232s which is really nice. 

Anyway, If I achieve a nice result (I hope soon), I will let you know.

Thank you again!

-Federico

**Comment by fede-vaccaro** [comment]
Hi, 
It's been some time since last time I update my project, but here it is: https://github.com/fede-vaccaro/TerrainEngine-OpenGL.
I didn't took anything in particular from your code, but you're thesis really helped me figuring out certain things about volumetric rendering! I quoted you in volumetric_clouds.frag shader. 

-Federico

**Comment by rikardolajos** [comment]
Hi,
I'm glad it helped you. It looks great! Much better than mine. Well done!
//Rikard
